---
title: "Week 03 Assignment 02_datasets"
author: "YOUR NAME HERE"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    citation_package: natbib
    latex_engine: pdflatex
    template: ./../latex-templates/homework.tex
    fig_caption: true
    number_sections: true
  html_document:
    df_print: paged
course: "STATS 419 Survey of Multivariate Analysis"
course-short: STATS419
instructor: Monte J. Shaffer




email: WSU email HERE


wsu-id: WSU ID HERE




---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,mychunk-1,message=FALSE}
library(devtools);  # devtools is required for function source_url() to work ...
my.source = 'github';
github.path = "https://raw.githubusercontent.com/MonteShaffer/WSU_STATS419_FALL2020/";
source_url( paste0(github.path,"master/functions/libraries.R") );
source_url( paste0(github.path,"master/functions/functions-imdb.R") );


```




Malcolm Gladwell\footnote{Comb your hair, man!} talks about outliers \citep{Gladwell:2008}.



\citet{Shaffer:2011} has a dissertation.


We would like to thank \citet{Rmarkdown:Latex:Templates} for the hints to create our own template...


