---
title: 'R Notebook: Intro'
author: "Sarah Ronchetti | 11515255"
output:
  html_document:
    df_print: paged
---
```{r}

github.monte = "https://raw.githubusercontent.com/MonteShaffer/"; 
include.me = paste0(github.monte, "humanVerseWSU/master/humanVerseWSU/R/functions-maths.R");

library(devtools); 
source_url(include.me); 

```

```{r}

which.github = "local"; 

github.local = "~/Desktop/WSU_STATS419_2021/sronchet/";
github.remote = "https://raw.../";

if(which.github == "remote")
{ 
  include.me = paste0( github.remote, "functions/functions-intro.R"); 
  library(devtools); 
  source_url(include.me); 
} else {
  include.me = paste0(github.local, "functions/functions-intro.R"); 
  source(include.me); 
}



```

# HandShake
```{r}
#HandShake Function
library(FRACTION); 
library(plotrix); 
library(pracma); 

is.wholenumber = function(x, tol = .Machine$double.eps^0.5)
{
  abs(x - round(x)) < tol; 
}
is.wholenumber(1)

handShake = function(n = 1, plotMe = TRUE)
{
  if(n < 1)
  {
    stop("Error"); 
  }
  
  if(!is.wholenumber(n))
  {
    stop("n must be an integer"); 
  }
  
  h = n*(n-1)/2;
  
  if(plotMe)
  {
    plot(0,0, type = "n", main = paste0(h, " Handshakes for ", n," People"), xlim = c(-6,6), ylim = c(-6,6), asp = 1, xlab = "", ylab = "", xaxt = "n", yaxt = "n", bty = "n"); 
      z = matrix(0, n, 2); 
      draw.circle(0,0,1); 
      x = 0; 
      y = 0; 
      
      points(x,y);
      #xs = c(xs, x); 
      #ys = c(ys, y); 
      
      for(i in 1:n) #points
      {
        x = round(cos(2 * pi * i/n), digits = 4); 
        y = round(sin(2 * pi * i/n), digits = 4); 
        #xn = x * cos(deg2rad(angle)) - y * sin(deg2rad(angle)); 
        #yn = y * cos(deg2rad(angle)) - x * sin(deg2rad(angle)); 
        points(x = x, y = y, cex = 3); 
        z[i,1] = x; 
        z[i,2] = y; 
      
      }
      
      #drawing a line segment from source to target
      for(j in 1:n) #source
      {
        for(k in 1:n) #target
        {
          segments(z[j,1], z[j,2], z[k,1], z[k,2]); 
        }
      }
  }
  
  h; 
}
```

# Alphabet Declaration of Independence 
```{r}
countingLettersStr = function(str, letter)
{
  nchar(as.character(str)) -nchar( gsub(letter, "", str, fixed = TRUE));
}

countingFreqLetters = function(str)
{
  str = gsub("[[:space:]]", "", str);
  str = tolower(str);
  df = data.frame(matrix(0, nrow = 1, ncol = 27, byrow = TRUE)); 
  colnames(df)=c(letters, "OTHER"); 
  for(letter in letters)
  {
    i = which(letters == letter); 
    df[1, i] = countingLettersStr(str, letter); 
    str = gsub(letter, "", str, fixed = TRUE); 
  }
  df[1, 27] = nchar(str); 
  df;
}
```

```{r}
library(DT)
path.declarationOfIndependence = paste0(github.local, "datasets/declarationOfIndependence/");
final = readChar(paste0(path.declarationOfIndependence, "final.txt"),99999);
draft = readChar(paste0(path.declarationOfIndependence, "draft.txt"),99999);

#Used the library(DT) to create a data table to display the different results  
df = NULL;
df = rbind(df, countingFreqLetters(draft));
df = rbind(df, countingFreqLetters(final));
rownames(df) = c("Draft", "Final");
datatable(df, colnames = c("a" = 2)) 
```

```{r}
prop = df; #proportion
prop[1, ] = prop[1, ] / sum(prop[1, ]);
prop[2, ] = prop[2, ] / sum(prop[2, ]);
rowSums(prop);
```

# Determinant of 3x3 matrix 
```{r}
computeDeterminant2 = function(myMatrix)
{
  nrow = nrow(myMatrix);
  ncol = ncol(myMatrix); 
  if(nrow != ncol)
  {
    stop("Matrix must be square"); 
  }
  if(nrow != 2)
  {
    stop("Matrix must be 2x2"); 
  }
  a = myMatrix[1,1];
  b = myMatrix[1,2];
  c = myMatrix[2,1];
  d = myMatrix[2,2];
  
  a * d - b * c; 
}


computeDeterminant3 = function(myMatrix)
{
  nrow = nrow(myMatrix);
  ncol = ncol(myMatrix); 
  if(nrow != ncol)
  {
    stop("Matrix must be square"); 
  }
  if(nrow != 3)
  {
    stop("Matrix must be 3x3"); 
  }
  a = myMatrix[1,1];
  b = myMatrix[1,2];
  c = myMatrix[1,3];
  d = myMatrix[2,1];
  e = myMatrix[2,2];
  f = myMatrix[2,3];
  g = myMatrix[3,1];
  h = myMatrix[3,2];
  i = myMatrix[3,3];
  
  a * computeDeterminant2(matrix(c(e,f,h,i), nrow = 2, byrow = TRUE)) - b * computeDeterminant2(matrix(c(d,f,g,i), nrow = 2, byrow = TRUE)) + c * computeDeterminant2(matrix(c(d,e,g,h), nrow = 2, byrow = TRUE)); 
}

```


```{r}
myMatrix = matrix(c(1,2,3,
                    4,5,6,
                    7,8,9), nrow = 3, byrow = TRUE); 

zeroIsh(det(myMatrix));
zeroIsh(computeDeterminant3(myMatrix));
```

```{r}
#We used the zeroIsh function to able to get a finite number of 0 instead of a number that is close to 0
myMatrix = matrix(c(4,8,25,
                    4,56,6,
                    7,45,9), nrow = 3, byrow = TRUE); 

zeroIsh(det(myMatrix));
zeroIsh(computeDeterminant3(myMatrix));
```



